"""Spanish source text and its English UI translations."""

import os


def system_language():
    """Use the OS display language; English covers unsupported languages."""
    if os.name == 'nt':
        import ctypes
        return 'es' if ctypes.windll.kernel32.GetUserDefaultUILanguage() & 0x3ff == 0x0a else 'en'
    locale_name = next((os.environ.get(name) for name in ('LANGUAGE', 'LC_ALL', 'LC_MESSAGES', 'LANG') if os.environ.get(name)), '')
    return 'es' if locale_name.split(':', 1)[0].lower().startswith('es') else 'en'

EN = {
    'Proxynas no incluye el SDK de Blackmagic RAW. Descárgalo una vez\ndesde la web oficial de Blackmagic:': 'Proxynas does not include the Blackmagic RAW SDK. Download it from the official Blackmagic website:',
    '1. Abre esa página y descarga el SDK para Windows.': '1. Open that page and download the Windows SDK.',
    '2. Vuelve a Proxynas y pulsa «Importar SDK BRAW (zip)».': '2. Return to Proxynas and click “Import BRAW SDK (zip)”.',
    '3. Elige el zip descargado: Proxynas copiará los ficheros necesarios.': '3. Choose the downloaded zip: Proxynas will copy the required files.',
    'Sin el SDK, todo sigue funcionando excepto los ficheros .braw.': 'Everything except .braw files works without the SDK.',
    'Proxynas descarga FFmpeg automáticamente la primera vez.\nEsta vez la descarga no ha funcionado: comprueba la conexión a\nInternet y vuelve a abrir Proxynas.\n\nSi tu red bloquea GitHub, descarga el zip a mano y copia ffmpeg.exe y\nffprobe.exe en la carpeta "portable\\bin", junto a Proxynas.exe.': 'Proxynas downloads FFmpeg automatically on first launch.\nThe download failed this time. Check your internet connection and reopen Proxynas.\n\nIf your network blocks GitHub, download the zip manually and copy ffmpeg.exe and ffprobe.exe into the "portable\\bin" folder next to Proxynas.exe.',
    'Proxies Blackmagic RAW y backup AV1 portable': 'Blackmagic RAW proxies and portable AV1 backup',
    'Minimizar al área de notificaciones': 'Minimize to notification area',
    'Modo oscuro': 'Dark mode',
    'Idioma': 'Language',
    'Carpeta vigilada': 'Watched folder',
    'Arrastra una carpeta o selecciónala. Proxies y backup trabajarán sobre este directorio.': 'Drop or choose a folder. Proxies and backup will use this directory.',
    'Genera proxies Resolve para BRAW y ProRes cuando falten.': 'Create missing Resolve proxies for BRAW and ProRes.',
    'Sincroniza lo nuevo hacia un destino y convierte vídeo a formatos ligeros.': 'Copy new files to a destination and convert video to smaller formats.',
    'Iniciar backup': 'Start backup',
    'Cancelar': 'Cancel',
    'Salir': 'Exit',
    'Hecho con ♥ por ': 'Made with ♥ by ',
    'Apoya el desarrollo': 'Support development',
    'Abrir carpeta': 'Open folder',
    'Arrastra la carpeta aquí': 'Drop the folder here',
    'o haz clic para abrirla': 'or click to choose it',
    'Crea proxies para el material profesional detectado en la carpeta vigilada: ahora, Blackmagic RAW y ProRes.': 'Create proxies for professional media in the watched folder: Blackmagic RAW and ProRes.',
    'Códec del proxy': 'Proxy codec',
    'Detectando códecs...': 'Detecting codecs...',
    'Selecciona una carpeta y crea proxies pendientes.': 'Choose a folder and create pending proxies.',
    'Modo live': 'Live mode',
    'Crear proxies pendientes': 'Create pending proxies',
    'Importar SDK BRAW (zip)': 'Import BRAW SDK (zip)',
    'Origen: carpeta vigilada superior': 'Source: watched folder above',
    'Destino del backup': 'Backup destination',
    'Examinar': 'Browse',
    'Qué respaldar': 'What to back up',
    'Todo': 'All',
    'Solo vídeo': 'Video only',
    'Audio + imágenes': 'Audio + images',
    'Otros': 'Other files',
    'Convertir vídeo': 'Convert video',
    'Códec de backup': 'Backup codec',
    'No transcodificar': 'Do not transcode',
    'Incluir originales BRAW en el backup (muy pesado)': 'Include original BRAW files in backup (very large)',
    'Apagar al terminar': 'Shut down when finished',
    'minutos:': 'minutes:',
    'Estado del sistema': 'System status',
    'Detectando...': 'Detecting...',
    'Actividad': 'Activity',
    'GPU (hardware)': 'GPU (hardware)',
    'CPU (software)': 'CPU (software)',
    'AV1 hardware': 'AV1 hardware',
    'H.265 hardware': 'H.265 hardware',
    'H.265 software': 'H.265 software',
    'activo': 'on',
    'inactivo': 'off',
    'Seleccionar carpeta vigilada': 'Choose watched folder',
    'Seleccionar directorio de origen': 'Choose source directory',
    'Seleccionar directorio de destino': 'Choose destination directory',
    'Selecciona el zip del Blackmagic RAW SDK': 'Choose the Blackmagic RAW SDK zip',
    'Todos los ficheros': 'All files',
    'Lo que has soltado no parece una carpeta válida.': 'The dropped item does not appear to be a valid folder.',
    'Carpeta lista. Puedes crear proxies o activar el modo live.': 'Folder ready. You can create proxies or enable live mode.',
    'Importando el SDK BRAW (puede tardar unos segundos)...': 'Importing the BRAW SDK (this may take a few seconds)...',
    'No se pudo importar el SDK BRAW.': 'Could not import the BRAW SDK.',
    'No se pudo importar el SDK BRAW:': 'Could not import the BRAW SDK:',
    'El SDK BRAW quedó incompleto. Revisa el aviso.': 'The BRAW SDK import is incomplete. Check the warning.',
    'SDK BRAW listo. Ya puedes crear proxies de .braw.': 'BRAW SDK ready. You can now create .braw proxies.',
    'SDK BRAW importado correctamente.': 'BRAW SDK imported successfully.',
    'Falta el decodificador braw_decode.exe en portable/bin/. No forma parte del SDK:\nlo incluye Proxynas, así que descarga de nuevo la última versión.': 'The braw_decode.exe decoder is missing from portable/bin/. It is included with Proxynas, not the SDK. Download the latest Proxynas release again.',
    'Para trabajar con BRAW, falta lo siguiente:': 'The following is missing for BRAW:',
    'Si ya tienes el zip del SDK descargado, Proxynas puede copiar por ti los\nficheros necesarios.\n\n¿Quieres importarlo ahora?': 'If you have downloaded the SDK zip, Proxynas can copy the required files.\n\nImport it now?',
    '¿Quieres abrir la página de descarga del SDK en el navegador?': 'Open the SDK download page in your browser?',
    '¿Quieres abrir la página de descarga en el navegador?': 'Open the download page in your browser?',
    'Selecciona una carpeta vigilada válida.': 'Choose a valid watched folder.',
    'Prueba con otro códec o con CPU.': 'Try another codec or CPU.',
    'Buscando material sin proxy...': 'Looking for media without proxies...',
    'Todo actualizado. No hay proxies pendientes.': 'Everything is up to date. No pending proxies.',
    'Proxies: todo actualizado.': 'Proxies: everything is up to date.',
    'Proxies creados.': 'Proxies created.',
    'Proxies finalizados.': 'Proxy creation finished.',
    'Modo live activo. Vigilando material nuevo...': 'Live mode on. Watching for new media...',
    'Modo live desactivado.': 'Live mode off.',
    'Backup live activo. Vigilando carpeta seleccionada...': 'Live backup on. Watching the selected folder...',
    'Backup live desactivado.': 'Live backup off.',
    'Mostrar Proxynas': 'Show Proxynas',
    'Bandeja del sistema no disponible en este entorno; minimizando a la barra de tareas.': 'System tray unavailable here; minimizing to the taskbar.',
    'Descargando FFmpeg (solo la primera vez)...': 'Downloading FFmpeg (first run only)...',
    'Descargando FFmpeg...': 'Downloading FFmpeg...',
    'FFmpeg listo.': 'FFmpeg ready.',
    'No se pudo descargar FFmpeg. Comprueba la conexión a Internet.': 'Could not download FFmpeg. Check your internet connection.',
    'No detectada': 'Not detected',
    'no encontrado en PATH': 'not found on PATH',
    'BRAW portable no disponible:': 'Portable BRAW unavailable:',
    'Conversión de vídeo desactivada para este modo.': 'Video conversion is disabled for this mode.',
    'No hay códecs de conversión disponibles; se copiará el vídeo original.': 'No conversion codecs are available; the original video will be copied.',
    'El directorio de origen no existe.': 'The source directory does not exist.',
    'no existe.': 'does not exist.',
    'Selecciona un directorio de destino.': 'Choose a destination directory.',
    'El destino del backup no puede estar dentro del origen.': 'The backup destination cannot be inside the source.',
    'Iniciando backup': 'Starting backup',
    'Backup cancelado por el usuario.': 'Backup cancelled by the user.',
    'Backup finalizado.': 'Backup finished.',
    'Cancelado. Deteniendo el archivo actual…': 'Cancelled. Stopping the current file…',
    'Uso:': 'Usage:',
    '<directorio_origen> <directorio_destino>': '<source_dir> <destination_dir>',
    'interfaz gráfica': 'graphical interface',
    'debes especificar un directorio de destino.': 'you must specify a destination directory.',
    'no se encuentra': 'could not find',
    'en PATH.': 'on PATH.',
    'En transferencia, se reintentará más tarde:': 'Still being transferred; will retry later:',
    'Cancelado:': 'Cancelled:',
    'Error procesando': 'Error processing',
    'Copiando imagen:': 'Copying image:',
    'Copiando vídeo:': 'Copying video:',
    'Copiando original:': 'Copying original:',
    'Copiado:': 'Copied:',
    'No se encontró en el zip:': 'Not found in the zip:',
    'Ya ': 'Already ',
    ', copiando:': ', copying:',
    'Transcodificando': 'Transcoding',
    'Reintentando': 'Retrying',
    'con conversión libplacebo': 'with libplacebo conversion',
    'Error de códec': 'Codec error',
    'finalizó con': 'exited with',
    'código': 'code',
    'sin detalle de FFmpeg': 'no FFmpeg details',
    'no disponible': 'unavailable',
    'sin encoder compatible en este ffmpeg': 'no compatible encoder in this FFmpeg build',
    'Sin encoder compatible en este ffmpeg': 'No compatible encoder in this FFmpeg build',
    'no listado por ffmpeg': 'not listed by FFmpeg',
    'ffmpeg no responde en': 'FFmpeg is not responding at',
    'ffmpeg no lista ningun encoder de video': 'FFmpeg lists no video encoders',
    'ffmpeg no lista encoders de vídeo': 'FFmpeg lists no video encoders',
    'falta FFmpeg': 'FFmpeg is missing',
    'Seleccionado:': 'Selected:',
    'Error fatal:': 'Fatal error:',
    'Error creando proxies:': 'Error creating proxies:',
    'Error en reconcile de proxies:': 'Error reconciling proxies:',
    'Encoder de proxy:': 'Proxy encoder:',
    'Proxies pendientes:': 'Pending proxies:',
    'Creando proxy': 'Creating proxy',
    'Reconciliado:': 'Reconciled:',
    ' movidos, ': ' moved, ',
    ' huérfanos, ': ' orphaned, ',
    ' nuevos.': ' new.',
    'Sin encoder': 'No encoder',
    ' de hardware': ' hardware',
    ' de software': ' software',
    'Saltando': 'Skipping',
    'No se encuentra': 'Could not find',
    'No se encuentra el ': 'Missing ',
    'El zip no trae ni DLL ni instalador (.msi) del SDK BRAW.': 'The zip contains no BRAW SDK DLL or installer (.msi).',
    'msiexec no pudo extraer el SDK': 'msiexec could not extract the SDK',
    'El instalador no traía un BlackmagicRawAPI.dll x64.': 'The installer did not contain an x64 BlackmagicRawAPI.dll.',
    'Se requiere un SDK BRAW': 'A BRAW SDK is required',
    'Decodificador BRAW portable': 'portable BRAW decoder',
    'SDK BRAW portable': 'portable BRAW SDK',
    ' en GPU (hardware) para los proxies.': ' on GPU (hardware) for proxies.',
    ' en CPU (software) para los proxies.': ' on CPU (software) for proxies.',
    'para proxies:': 'for proxies:',
    'No hay ningún encoder': 'No encoder is available for',
    'para los proxies.': 'proxies.',
    'Drag & drop nativo no disponible:': 'Native drag and drop unavailable:',
    'Archivos a procesar:': 'Files to process:',
    'Origen:': 'Source:',
    'Destino:': 'Destination:',
    'Modo:': 'Mode:',
    'Transcodificar:': 'Transcode:',
    'Sí': 'Yes',
    'Códec de backup:': 'Backup codec:',
    'Imágenes': 'Images',
    'Vídeos': 'Videos',
    'Vídeo': 'Video',
    'Copiados': 'Copied',
    'Saltados': 'Skipped',
    'Errores': 'Errors',
    'archivos': 'files',
    'Otros archivos': 'Other files',
    'El equipo se apagará en': 'The computer will shut down in',
    'minuto': 'minute',
    'Apagar': 'Shut down',
    'Perfil de audio desconocido:': 'Unknown audio preset:',
    'Herramientas BRAW no disponibles:': 'BRAW tools unavailable:',
    'Encoder': 'Encoder',
    'Salida temporal inválida:': 'Invalid temporary output:',
    'No se pudo guardar el registro de proxies:': 'Could not save the proxy registry:',
    'Escaneo vacío: no se procesan huérfanos (¿unidad desconectada?).': 'Empty scan: orphaned proxies were not processed (drive disconnected?).',
    'Escaneo precavido:': 'Cautious scan:',
    'archivos. No se procesan huérfanos.': 'files. Orphaned proxies were not processed.',
    'Proxy movido:': 'Proxy moved:',
    'Proxy a _orphan/ (colision):': 'Proxy moved to _orphan/ (collision):',
    'Proxy huérfano:': 'Orphaned proxy:',
    'sin source tras': 'source missing after',
    'escaneos': 'scans',
    'Error moviendo proxy': 'Error moving proxy',
    'Error cuarentenando proxy': 'Error quarantining proxy',
    'Buscando vídeos en:': 'Looking for videos in:',
    'No se encontraron vídeos para analizar.': 'No videos found to analyze.',
    'Analizando archivos y proxies existentes...': 'Checking files and existing proxies...',
    'parece estar en transferencia.': 'appears to still be transferring.',
    'Todo actualizado. No hay vídeos nuevos que procesar.': 'Everything is up to date. No new videos to process.',
    'Se procesarán': 'Processing',
    'vídeos nuevos.': 'new videos.',
    'TRABAJO': 'JOB',
    'ÉXITO: proxy creado para': 'SUCCESS: proxy created for',
    'Proceso de creación de proxies finalizado': 'Proxy creation finished',
    'Generador de Proxies Portable BRAW SDK': 'Portable BRAW SDK Proxy Generator',
    'Directorio de trabajo:': 'Working directory:',
    'ERROR CRÍTICO:': 'CRITICAL ERROR:',
    'Proxynas - resumen de diagnóstico': 'Proxynas - diagnostic summary',
    'Proxynas - diagnóstico de encoders': 'Proxynas - encoder diagnostics',
    'Equipo:': 'Computer:',
    'FALLO': 'FAILED',
    'BRAW opcional para la prueba real': 'Optional BRAW file for the real test',
    'Puede tardar varios minutos. Los fallos de GPU no instalada son normales.': 'This may take several minutes. Failures for GPUs that are not installed are expected.',
    'No existe:': 'Does not exist:',
    'Terminado.': 'Finished.',
}


def translate(text, language='es'):
    if language != 'en':
        return text
    for spanish, english in sorted(EN.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(spanish, english)
    return text
